### ISSUE TITLE
Node JS microservice is not registered properly in Jhipster Registry

### ISSUE THREAD

**Issue by ajoysinhactc** [jhipster/generator-jhipster-nodejs#103]
**Describe the bug**
NodeJS microservices is not registered properly in Jhipster Registry

**To Reproduce**

- Create a Nodejs Micro service using Jhipster blueprint = node js
- Run Jhipster registery
- Run the node js application
- Instance ID is displaying as usermicroservice:undefined

**Screenshot attached**

**Expected behavior**

usermicroservice:**<<Instance ID>>** should bedisplayed

**Screenshots**

![image](https://user-images.githubusercontent.com/49013287/74160060-d3039000-4c42-11ea-9ccc-f391be4a50a8.png)

**Comment by amanganiello90** [comment]
Hi @ajoysinhactc ,
thanks for your feedback!
The feature that you want, maybe is not implemented yet.
But, we can do it in the next release.
Could you please to add your yo-rc.json to get more information?
Thanks

**Comment by ajoysinhactc** [comment]
yo-rc.json addaed as requested


[yo-rc.json.txt](https://github.com/jhipster/generator-jhipster-nodejs/files/4181607/yo-rc.json.txt)

**Comment by amanganiello90** [comment]
Thanks. Please attention that you are using an old version of the nodejs blueprint (1.0.0-beta.2).

**Comment by jlopezjuy** [comment]
@amanganiello90  Hi, my name is Juan, im from Jujuy Argentina, I have a question with nhipster microservices, when i create a microservice this create user and roles, it's ok? on jhipster microservice this entities don't created. Could you help me?

**Comment by amanganiello90** [comment]
Hi @jlopezjuy,
thanks for the interest!
Yes, there are roles and users created according this [seed file](https://github.com/jhipster/jhipster-sample-app-nodejs/blob/v1.1.0/server/src/migrations/1570200490072-SeedUsersRoles.ts) as jhipster standard, executed in the microservice startup. However this issue is not the topic of your question.
Please add on [gitter](https://gitter.im/generator-jhipster-nodejs/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) or open another issue. Thanks.

**Comment by jlopezjuy** [comment]
I have the same error like Ajoy
`{
  "generator-jhipster": {
    "jhipsterVersion": "6.8.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.jhipster.node",
    "packageFolder": "com/jhipster/node",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "creationTimestamp": 1599004988219,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.1.0"
      }
    ],
    "enableTranslation": false,
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "1.1.0"
      }
    ],
    "promptValues": {
      "microservicePath": "/home/jlopezjuy/Proyectos/Bintelligence/TestMicros/documentos"
    }
  }
}
`


App | Instance ID | Status
-- | -- | --
DOCUMENTOS | documentos:undefined | UP
GATEWAY | gateway:undefined | UP

**Comment by OmidPoorali** [comment]
i solved this NullPointerException problem by adding "homePageUrl" in instance object
in my case :

           instance: {
                hostName: ip.address(),
                instanceId: `${appName}:${serviceID}`,
                vipAddress: `${appName}`,
                app: `${appName.toUpperCase()}`,
                ipAddr: ip.address(),
                status: `UP`,
                port: {
                    $: port,
                    "@enabled": true
                },
                homePageUrl: `http://${ip.address()}:${port}/`,
                dataCenterInfo: {
                    "@class": `com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo`,
                    name: `MyOwn`
                }
            }

**Comment by amanganiello90** [comment]
@OmidPoorali  Thanks for the suggestion! I have reported your fix on the https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/issue-103 

Could you test it with a generation? Thanks

**Comment by jlopezjuy** [comment]
Hi in my case i add status: 'UP', 
```
instance: {
        app: config.get('eureka.instance.appname').toUpperCase(),
        instanceId: config.get('eureka.instance.instanceId'),
        hostName: config.get('ipAddress') || 'localhost',
        ipAddr: config.get('ipAddress') || '127.0.0.1',
        status: 'UP',
        port: {
          $: port,
          '@enabled': 'true'
        },
        vipAddress: config.get('eureka.instance.appname'),
        statusPageUrl: `http://${config.get('ipAddress')}:${port}/`,
        dataCenterInfo: {
          '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
          name: 'MyOwn'
        }
      },
```

**Comment by amanganiello90** [comment]
@jlopezjuy  yes, maybe status up is already the default (if not defined). But homePageUrl could be mandatory

**Comment by jlopezjuy** [comment]
```
Here my main.ts
require('dotenv').config({ path: '.env' });
import { NestFactory } from '@nestjs/core';
import cloudConfigClient from 'cloud-config-client';
import { AppModule } from './app.module';
import { setupSwagger } from './swagger';
import { config } from './config';
import { Logger, ValidationPipe, BadRequestException } from '@nestjs/common';
import * as express from 'express';
import * as path from 'path';
import * as fs from 'fs';
const logger: Logger = new Logger('Main');
const port = process.env.NODE_SERVER_PORT || config.get('server.port');
const useJHipsterRegistry = config.get('eureka.client.enabled');

async function bootstrap(): Promise<void> {
  loadCloudConfig();
  registerAsEurekaService();

  const appOptions = { cors: true };
  const app = await NestFactory.create(AppModule, appOptions);
  app.useGlobalPipes(
    new ValidationPipe({
      exceptionFactory: (): BadRequestException => new BadRequestException('Validation error')
    })
  );

  const staticClientPath = path.join(__dirname, '../dist/classes/static');
  if (fs.existsSync(staticClientPath)) {
    app.use(express.static(staticClientPath));
    logger.log(`Serving static client resources on ${staticClientPath}`);
  } else {
    logger.log(`No client it has been found`);
  }

  setupSwagger(app);

  await app.listen(port);
  logger.log(`Application listening on port ${port}`);
}

async function loadCloudConfig(): Promise<void> {
  if (useJHipsterRegistry) {
    const endpoint = config.get('cloud.config.uri') || 'http://admin:admin@localhost:8761/config';
    logger.log(`Loading cloud config from ${endpoint}`);

    const cloudConfig = await cloudConfigClient.load({
      context: process.env,
      endpoint,
      name: config.get('cloud.config.name'),
      profiles: config.get('cloud.config.profile') || ['prod'],
      auth: {
        user: 'admin',
        pass: 'admin'
      }
    });
    config.addAll(cloudConfig.properties);
  }
}

function registerAsEurekaService(): void {
  if (useJHipsterRegistry) {
    logger.log(`Registering with eureka ${config.get('cloud.config.uri')}`);
    const Eureka = require('eureka-js-client').Eureka;
    const eurekaUrl = require('url').parse(config.get('cloud.config.uri'));
    const client = new Eureka({
      instance: {
        app: config.get('eureka.instance.appname').toUpperCase(),
        instanceId: config.get('eureka.instance.instanceId'),
        hostName: config.get('ipAddress') || 'localhost',
        ipAddr: config.get('ipAddress') || '127.0.0.1',
        status: 'UP',
        port: {
          $: port,
          '@enabled': 'true'
        },
        vipAddress: config.get('eureka.instance.appname'),
        statusPageUrl: `http://${config.get('ipAddress')}:${port}/`,
        homePageUrl: `http://${config.get('ipAddress')}:${port}/`,
        dataCenterInfo: {
          '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
          name: 'MyOwn'
        }
      },
      eureka: {
        // eureka server host / port
        host: eurekaUrl.hostname || '127.0.0.1',
        port: eurekaUrl.port || 8761,
        servicePath: '/eureka/apps'
      },
      requestMiddleware: (requestOpts, done): any => {
        requestOpts.auth = {
          user: 'admin',
          password: 'admin'
        };
        done(requestOpts);
      }
    });
    client.logger.level('debug');
    client.start(error => logger.log(error || 'Eureka registration complete'));
  }
}

bootstrap();

```

**Comment by amanganiello90** [comment]
@jlopezjuy  could you try a new generation using the branch https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/issue-103?
Please check if it works. Thanks

**Comment by jlopezjuy** [comment]
ok, I'll chek. 
off-topic question, did you use this configuration? "client.getInstancesByAppId"  to communicate directly every micro service?

**Comment by amanganiello90** [comment]
> 
> 
> ok, I'll chek.
> off-topic question, did you use this configuration? "client.getInstancesByAppId" to communicate directly every micro service?

I don't know if it is used because the eureka features is done from a contributor that tested it. I haven't experience on that usage. So every contribution to improve that is welcome :) .

**Comment by jlopezjuy** [comment]
ok, did you have npm command to install feature 103?

**Comment by amanganiello90** [comment]
> 
> 
> ok, did you have npm command to install feature 103?

Follow the steps to install locally the generator from the repository: https://github.com/jhipster/generator-jhipster-nodejs#-steps-to-develop-a-generator-feature-and-test-it

**Comment by jlopezjuy** [comment]
great, tnks

**Comment by jlopezjuy** [comment]
i have this error: @amanganiello90 
```
? Which *type* of application would you like to create? Microservice application
? What is the base name of your application? testms
events.js:292
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'call' of undefined
    at JHipsterAppGenerator.setupSharedOptions (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster/generators/generator-base.js:2122:33)
    at JHipsterAppGenerator.setupServerOptions (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster/generators/generator-base.js:2151:14)
    at new module.exports (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/generators/server/index.js:21:19)
    at Environment.instantiate (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster/node_modules/yeoman-environment/lib/environment.js:673:23)
    at instantiate (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/node_modules/yeoman-generator/lib/index.js:811:23)
    at module.exports.composeWith (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/node_modules/yeoman-generator/lib/index.js:840:33)
    at module.exports.composeServer (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/generators/app/index.js:124:22)
    at Object.<anonymous> (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/node_modules/yeoman-generator/lib/index.js:647:25)
    at /media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/media/jlopezjuy/Datos/proyectos/jhipsterNodejs/generator-jhipster-nodejs/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:456:21)
    at process
```

**Comment by amanganiello90** [comment]
Hi @jlopezjuy , try to perform the following under generator-jhipster repository:

``
git checkout v6.8.0
``

**Comment by jlopezjuy** [comment]
Here's the new main.ts using feature 103: @amanganiello90 
```
require('dotenv').config({ path: '.env' });
import { NestFactory } from '@nestjs/core';
import cloudConfigClient from 'cloud-config-client';
import { AppModule } from './app.module';
import { setupSwagger } from './swagger';
import { config } from './config';
import { Logger, ValidationPipe, BadRequestException } from '@nestjs/common';
import * as express from 'express';
import * as path from 'path';
import * as fs from 'fs';
const logger: Logger = new Logger('Main');
const port = process.env.NODE_SERVER_PORT || config.get('server.port');
const useJHipsterRegistry = config.get('eureka.client.enabled');

async function bootstrap(): Promise<void> {
  loadCloudConfig();
  registerAsEurekaService();

  const appOptions = { cors: true };
  const app = await NestFactory.create(AppModule, appOptions);
  app.useGlobalPipes(
    new ValidationPipe({
      exceptionFactory: (): BadRequestException => new BadRequestException('Validation error')
    })
  );

  const staticClientPath = path.join(__dirname, '../dist/classes/static');
  if (fs.existsSync(staticClientPath)) {
    app.use(express.static(staticClientPath));
    logger.log(`Serving static client resources on ${staticClientPath}`);
  } else {
    logger.log(`No client it has been found`);
  }

  setupSwagger(app);

  await app.listen(port);
  logger.log(`Application listening on port ${port}`);
}

async function loadCloudConfig(): Promise<void> {
  if (useJHipsterRegistry) {
    const endpoint = config.get('cloud.config.uri') || 'http://admin:admin@localhost:8761/config';
    logger.log(`Loading cloud config from ${endpoint}`);

    const cloudConfig = await cloudConfigClient.load({
      context: process.env,
      endpoint,
      name: config.get('cloud.config.name'),
      profiles: config.get('cloud.config.profile') || ['prod']
      // auth: {
      //   user: config.get('jhipster.registry.username') || 'admin',
      //   pass: config.get('jhipster.registry.password') || 'admin'
      // }
    });
    config.addAll(cloudConfig.properties);
  }
}

function registerAsEurekaService(): void {
  if (useJHipsterRegistry) {
    logger.log(`Registering with eureka ${config.get('cloud.config.uri')}`);
    const Eureka = require('eureka-js-client').Eureka;
    const eurekaUrl = require('url').parse(config.get('cloud.config.uri'));
    const client = new Eureka({
      instance: {
        app: config.get('eureka.instance.appname'),
        instanceId: config.get('eureka.instance.instanceId'),
        hostName: config.get('ipAddress') || 'localhost',
        ipAddr: config.get('ipAddress') || '127.0.0.1',
        port: {
          $: port,
          '@enabled': 'true'
        },
        vipAddress: config.get('ipAddress') || 'localhost',
        statusPageUrl: `http://${config.get('ipAddress')}:${port}/`,
        dataCenterInfo: {
          '@class': 'com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo',
          name: 'MyOwn'
        }
      },
      eureka: {
        // eureka server host / port
        host: eurekaUrl.hostname || '127.0.0.1',
        port: eurekaUrl.port || 8761,
        servicePath: '/eureka/apps'
      },
      requestMiddleware: (requestOpts, done): any => {
        requestOpts.auth = {
          user: config.get('jhipster.registry.username') || 'admin',
          password: config.get('jhipster.registry.password') || 'admin'
        };
        done(requestOpts);
      }
    });
    client.logger.level('debug');
    client.start(error => logger.log(error || 'Eureka registration complete'));
  }
}

bootstrap();
```

**Comment by amanganiello90** [comment]
Thanks @jlopezjuy, but it works as your expectation?

**Comment by jlopezjuy** [comment]
yes

**Comment by amanganiello90** [comment]
@jlopezjuy  thanks a lot! If you want to contribute or give any suggestions you are welcome! 💯
