### ISSUE TITLE
Cannot compile app::  src/web/rest/user.controller.ts:29:54 - error TS2345: Argument of type 'string | Query | (string | Query)[]' is not assignable to parameter of type 'string | number'.  

### ISSUE THREAD

**Issue by stisko** [jhipster/generator-jhipster-nodejs#126]
After following all the instructions, from the readme, i cannot run my application (the same happens on sample app nodejs. 

This error message appears.

```
  return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/web/rest/user.controller.ts:29:54 - error TS2345: Argument of type 'string | Query | (string | Query)[]' is not assignable to parameter of type 'string | number'.
  Type 'Query' is not assignable to type 'string | number'.
    Type 'Query' is not assignable to type 'string'.

29     const pageRequest: PageRequest = new PageRequest(req.query.page, req.query.size, req.query.sort);
                                                        ~~~~~~~~~~~~~~

    at createTSError (C:\Users\uname\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:240:12)
    at reportTSError (C:\Users\unmae\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:244:19)
    at getOutput (C:\Users\uname\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:360:34)
    at Object.compile (C:\Users\uname\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:393:11)
    at Module.m._compile (C:\Users\uname\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\uname\Desktop\test\jhipster-sample-app-nodejs-master\server\node_modules\ts-node\src\index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
[nodemon] app crashed - waiting for file changes before starting...
```

Why this happen?

**Comment by amanganiello90** [comment]
Linked to #120
