### ISSUE TITLE
Sqlite3 v4.0.9 cannot start with nodejs v12.16.x

### ISSUE THREAD

**Issue by Aragonbn90** [jhipster/generator-jhipster-nodejs#130]
**Describe the bug**
Sqlite3 v4.0.9 cannot start with nodejs v12.16.x

**To Reproduce**

1. Use JHipster version 6.8.0
2. Create monolithic NHipster app
3. Run app with `npm run start:app`
`
[Nest] 7512   - 05/01/2020, 6:15 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +2998ms
DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at new DriverPackageNotInstalledError (APP\server\src\error\DriverPackageNotInstalledError.ts:8:9)
    at SqliteDriver.loadDependencies (APP\server\src\driver\sqlite\SqliteDriver.ts:128:19)
    at new SqliteDriver (APP\server\src\driver\sqlite\SqliteDriver.ts:46:14)
    at DriverFactory.create (APP\server\src\driver\DriverFactory.ts:37:24) 
    at new Connection (APP\server\src\connection\Connection.ts:125:43)     
    at ConnectionManager.create (APP\server\src\connection\ConnectionManager.ts:64:28)
    at Object.<anonymous> (APP\server\src\index.ts:225:35)
    at step (APP\server\node_modules\tslib\tslib.js:139:27)
    at Object.next (APP\server\node_modules\tslib\tslib.js:120:57)
    at APP\server\node_modules\tslib\tslib.js:113:75
`
**Expected behavior**
App runs with both frontend and backend
-   OS: Windows 10

**Additional context**
JHipster 6.8.0 runs with nodejs version >= 12.16.1
Sqlite v4.0.9 runs with nodejs version < 12.16.1
We need to change sqlite3 version to 4.2.0

**Comment by amanganiello90** [comment]
Hi Ed,
Are you sure? We have integration tests pipeline on github actions with node 12.16.2.

**Comment by Aragonbn90** [comment]
Oh, I've rechecked.
Maybe because I'm using dev version on my local. After I unlink jhipster and nhipster dev version, then reinstall them, there's no error.
Sorry because this mistake.
