### ISSUE TITLE
Does node NestJS server with client (angular, react or vue) work?

### ISSUE THREAD

**Issue by wurst44** [jhipster/generator-jhipster-nodejs#210]
Just curious, does node + react / node + vue work?
Setup is the same as in: https://github.com/jhipster/generator-jhipster-nodejs/issues/209
Except,

node + react:
```
$ npm run build
> bubilove@0.0.1 build /builds/serge/apps/jhipster-generator/server
> npm run clean && tsc -p tsconfig.build.json && npm run copy-resources
> bubilove@0.0.1 clean /builds/serge/apps/jhipster-generator/server
> rimraf dist ../target/db/
src/domain/post.entity.ts(5,10): error TS2305: Module '"./blog.entity"' has no exported member 'Blog'.
src/domain/post.entity.ts(6,10): error TS2305: Module '"./tag.entity"' has no exported member 'Tag'.
src/domain/tag.entity.ts(5,10): error TS2305: Module '"./post.entity"' has no exported member 'Post'.
src/repository/blog.repository.ts(2,10): error TS2305: Module '"../domain/blog.entity"' has no exported member 'Blog'.
src/repository/post.repository.ts(2,10): error TS2305: Module '"../domain/post.entity"' has no exported member 'Post'.
src/repository/tag.repository.ts(2,10): error TS2305: Module '"../domain/tag.entity"' has no exported member 'Tag'.
src/service/blog.service.ts(4,10): error TS2305: Module '"./dto/blog.dto"' has no exported member 'BlogDTO'.
src/service/blog.service.ts(5,10): error TS2305: Module '"./mapper/blog.mapper"' has no exported member 'BlogMapper'.
src/service/dto/post.dto.ts(6,10): error TS2305: Module '"./blog.dto"' has no exported member 'BlogDTO'.
src/service/dto/post.dto.ts(7,10): error TS2305: Module '"./tag.dto"' has no exported member 'TagDTO'.
src/service/dto/tag.dto.ts(6,10): error TS2305: Module '"./post.dto"' has no exported member 'PostDTO'.
src/service/post.service.ts(4,10): error TS2305: Module '"./dto/post.dto"' has no exported member 'PostDTO'.
src/service/post.service.ts(5,10): error TS2305: Module '"./mapper/post.mapper"' has no exported member 'PostMapper'.
src/service/tag.service.ts(4,10): error TS2305: Module '"./dto/tag.dto"' has no exported member 'TagDTO'.
src/service/tag.service.ts(5,10): error TS2305: Module '"./mapper/tag.mapper"' has no exported member 'TagMapper'.
src/web/rest/blog.controller.ts(4,10): error TS2305: Module '"../../service/dto/blog.dto"' has no exported member 'BlogDTO'.
src/web/rest/post.controller.ts(4,10): error TS2305: Module '"../../service/dto/post.dto"' has no exported member 'PostDTO'.
src/web/rest/tag.controller.ts(4,10): error TS2305: Module '"../../service/dto/tag.dto"' has no exported member 'TagDTO'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! bubilove@0.0.1 build: `npm run clean && tsc -p tsconfig.build.json && npm run copy-resources`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the bubilove@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-26T11_01_59_932Z-debug.log
```

AND

node + vue:
```
$ jhipster jdl $ENTITY_CONF --no-insight --skip-install --skip-checks;
INFO! Using JHipster version installed globally
INFO! Executing import-jdl blog.jh
INFO! The JDL is being parsed.
warn: An Entity name 'User' was used: 'User' is an entity created by default by JHipster. All relationships toward it will be kept but any attributes and relationships from it will be disregarded.
INFO! Found entities: Blog, Post, Tag.
INFO! The JDL has been successfully parsed
INFO! Generating 1 application.
INFO! Generating application bubilove in a new parallel process
INFO! No custom sharedOptions found within blueprint: generator-jhipster-vuejs at /usr/lib/node_modules/generator-jhipster-vuejs
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at /usr/lib/node_modules/generator-jhipster-nodejs
INFO! Executing jhipster:app on /builds/serge/apps/jhipster-generator
     info Using blueprint generator-jhipster-nodejs for app subgenerator
(node:50) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:50) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'sed' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'set' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'sort' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'tail' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'test' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'to' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'toEnd' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'touch' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'uniq' of module exports inside circular dependency
(node:50) Warning: Accessing non-existent property 'which' of module exports inside circular dependency
 ███╗   ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗  ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔██╗ ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╗██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚████║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝  ╚═══╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to NHipster (Jhipster NodeJS Official Blueprint) v1.4.0
This blueprint generates your backend in NodeJS with NestJS framework
 _______________________________________________________________________________________________________________
  For any questions or improvements refer to the stream lead at https://github.com/amanganiello90
  If you find NHipster useful, support and star the project at https://github.com/jhipster/generator-jhipster-nodejs
 _______________________________________________________________________________________________________________
 This NodeJS blueprint use these following configurations:
 1. NestJS Framework with swagger doc
 2. JWT or OAuth2 Passport security authentication
 3. TypeORM usage with SQLite development database and versioning/migration
 4. Initial load data seed with users (using auth roles) integrated with the angular/react client
 5. Eureka JS client registry
This is an existing project, using the configuration from your .yo-rc.json file 
to re-generate the project...
     info Using blueprint generator-jhipster-vuejs for languages subgenerator
     info Using blueprint generator-jhipster-nodejs for languages subgenerator
Installing languages: en, de
Installing languages: en, de for client
Found the .jhipster/Blog.json configuration file, entity can be automatically generated!
The entity Blog is being updated.
Found the .jhipster/Post.json configuration file, entity can be automatically generated!
The entity Post is being updated.
Found the .jhipster/Tag.json configuration file, entity can be automatically generated!
The entity Tag is being updated.
Unable to find src/main/webapp/app/shared/config/store/translation-store.ts or missing required jhipster-needle. Language pipe not updated with languages: en,de since block was not found. Check if you have enabled translation support.
Unable to find src/main/webapp/app/shared/config/config.ts or missing required jhipster-needle. Language pipe not updated with languages: en,de since block was not found. Check if you have enabled translation support.
     info Using blueprint generator-jhipster-vuejs for entity-client subgenerator
     info Using blueprint generator-jhipster-vuejs for entity-client subgenerator
     info Using blueprint generator-jhipster-vuejs for entity-client subgenerator
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: /builds/serge/apps/jhipster-generator/src/main/webapp/app/core/jhi-navbar/jhi-navbar.vue doesn't exist
    at EditionInterface.module.exports [as read] (/usr/lib/node_modules/generator-jhipster-vuejs/node_modules/yeoman-generator/node_modules/mem-fs-editor/lib/actions/read.js:12:11)
    at Object.rewriteFile (/usr/lib/node_modules/generator-jhipster-vuejs/node_modules/generator-jhipster/generators/utils.js:88:34)
    at Object.addEntityToMenu (/usr/lib/node_modules/generator-jhipster-vuejs/generators/utils.js:181:19)
    at module.exports.writeFiles (/usr/lib/node_modules/generator-jhipster-vuejs/generators/entity-client/files.js:180:15)
    at module.exports.writeAdditionalFile (/usr/lib/node_modules/generator-jhipster-vuejs/generators/entity-client/index.js:13:28)
    at Object.<anonymous> (/usr/lib/node_modules/generator-jhipster-vuejs/node_modules/yeoman-generator/lib/index.js:976:25)
    at /usr/lib/node_modules/generator-jhipster-vuejs/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /usr/lib/node_modules/generator-jhipster-vuejs/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/usr/lib/node_modules/generator-jhipster-vuejs/node_modules/yeoman-generator/lib/index.js:977:11)
Emitted 'error' event on Generator instance at:
    at Immediate.<anonymous> (/usr/lib/node_modules/generator-jhipster-vuejs/node_modules/yeoman-generator/lib/index.js:1007:20)
    at processImmediate (internal/timers.js:461:21)
INFO! App: child process exited with code 1
ERROR! JHipster finished with code 1
ERROR: Job failed: exit code 1
```

thx for the great work!!

**Comment by amanganiello90** [comment]
Hi @wurst44 ,
thanks for the interest!
I'm now working for vue support (after migrating to the jhipster 7.0.0) on [vuejs branch](https://github.com/jhipster/generator-jhipster-nodejs/tree/feature/vue-issue158).
For react I have not understood what generation you have performed.
However, wait for the next nhipster 2.0.0-beta.1 version, that will have the previous branch merged (as explained in #158)

**Comment by amanganiello90** [comment]
I hope that my explanation is been clear. So I consider this question/issue resolved.

**Comment by wurst44** [comment]
thank you for explanation and your effort.
Am I correct that this is in code review now?

**Comment by amanganiello90** [comment]
Hi @wurst44 , you can try with the new 2.0.0-beta.1 version. It works in the test integration pipeline
