### ISSUE TITLE
v2.0.0-beta.1 - fails to npm install command

### ISSUE THREAD

**Issue by pwujek** [jhipster/generator-jhipster-nodejs#227]
**Describe the bug**
`npm install` step in app generation fails with errors in initial build of very simple React/MySQL app.

**To Reproduce**
```bash
paul@Lenovo:~/Desktop/aaa/project
$ mkdir test;cd test
paul@Lenovo:~/Desktop/aaa/project/test
$ nhipster app
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at /home/paul/.nvm/versions/node/v14.16.0/lib/node_modules/generator-jhipster-nodejs
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at /home/paul/.nvm/versions/node/v14.16.0/lib/node_modules/generator-jhipster-nodejs
INFO! Error parsing options for generator jhipster-nodejs:app, error: Error: This is a JHipster blueprint and should be used only like jhipster --blueprints nodejs
     info Using blueprint generator-jhipster-nodejs for app subgenerator


 ███╗   ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗  ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔██╗ ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╗██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚████║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝  ╚═══╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to NHipster (Jhipster NodeJS Official Blueprint) v2.0.0-beta.1
This blueprint generates your backend in NodeJS with NestJS framework
 _______________________________________________________________________________________________________________

  For any questions or improvements refer to the stream lead at https://github.com/amanganiello90
  If you find NHipster useful, support and star the project at https://github.com/jhipster/generator-jhipster-nodejs
 _______________________________________________________________________________________________________________

 This NodeJS blueprint use these following configurations:

 1. NestJS Framework with swagger doc

 2. JWT or OAuth2 Passport security authentication

 3. TypeORM usage with SQLite development database and versioning/migration

 4. Initial load data seed with users (using auth roles) integrated with the angular/react client

 5. Eureka JS client registry

 ______________________________________________________________________________

  JHipster update available: 7.0.1 (current: 7.0.0)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? test
     info Using blueprint generator-jhipster-nodejs for common subgenerator
     info Using blueprint generator-jhipster-nodejs for server subgenerator
     info Using blueprint generator-jhipster-nodejs for client subgenerator
     info Using blueprint generator-jhipster-nodejs for languages subgenerator
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *production* database would you like to use? MySQL or MariaDB
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Would you like to install other generators from the JHipster Marketplace? No
   create .prettierrc
   create .prettierignore
   create .gitattributes
   create .editorconfig
   create .gitignore
   create sonar-project.properties
   create .huskyrc
   create .dockerignore
   create Dockerfile
   create package.json
    force .yo-rc-global.json
    force .yo-rc.json
   create README.md
   create .lintstagedrc.js
   create server/src/web/rest/user.controller.ts
   create server/src/web/rest/account.controller.ts
   create server/src/web/rest/public.user.controller.ts
   create server/src/web/rest/management.controller.ts
   create server/src/repository/user.repository.ts
   create server/src/repository/authority.repository.ts
   create server/src/module/user.module.ts
   create server/src/module/auth.module.ts
   create server/src/config/application-dev.yml
   create server/src/config/application-test.yml
   create server/src/config.ts
   create server/.env
   create server/.server.eslintrc.json
   create server/.server.eslintignore
   create server/src/config/application-prod.yml
   create server/.prettierrc.js
   create server/src/config/application.yml
   create server/src/domain/base/pagination.entity.ts
   create server/src/domain/base/base.entity.ts
   create server/src/domain/user.entity.ts
   create server/src/domain/authority.entity.ts
   create server/src/security/guards/roles.guard.ts
   create server/src/security/guards/auth.guard.ts
   create server/src/security/role-type.ts
   create server/src/security/decorators/auth-user.decorator.ts
   create server/src/security/decorators/roles.decorator.ts
   create server/src/security/index.ts
   create server/src/client/header-util.ts
   create server/src/client/interceptors/logging.interceptor.ts
   create server/src/service/auth.service.ts
   create server/src/service/user.service.ts
   create server/sonar-project.properties
   create webpack/logo-jhipster.png
   create .npmrc
   create server/src/service/dto/base.dto.ts
   create server/src/service/dto/user.dto.ts
   create server/src/service/mapper/user.mapper.ts
   create server/src/main.ts
   create server/src/swagger.ts
   create server/src/app.module.ts
   create server/src/migrations/1570200270081-CreateTables.ts
   create server/src/migrations/1570200490072-SeedUsersRoles.ts
   create server/src/orm.config.ts
   create server/scripts/copy-resources.ts
   create server/tsconfig.build.json
   create server/test/admin/management.controller.spec.ts
   create server/nest-cli.json
   create server/package.json
   create server/tsconfig.json
   create server/README.md
   create server/webpack.server.prod.config.js
   create server/e2e/app.e2e-spec.ts
   create server/e2e/user.e2e-spec.ts
   create server/e2e/jest.e2e.config.json
   create server/e2e/setup.test.js
   create server/e2e/account.e2e-spec.ts
   create src/main/docker/app.yml
   create src/main/docker/sonar.yml
   create server/src/web/rest/user.jwt.controller.ts
   create server/src/security/passport.jwt.strategy.ts
   create server/src/security/payload.interface.ts
   create server/src/service/dto/password-change.dto.ts
   create server/src/service/dto/user-login.dto.ts
   create src/main/docker/mysql.yml
   create .eslintrc.json
   create tsconfig.json
   create tsconfig.test.json
   create jest.conf.js
   create webpack/webpack.common.js
   create webpack/webpack.dev.js
   create webpack/webpack.prod.js
   create webpack/utils.js
   create tsconfig.e2e.json
   create postcss.config.js
   create src/main/webapp/app/app.tsx
   create src/main/webapp/app/index.tsx
   create src/main/webapp/app/routes.tsx
   create src/main/webapp/app/setup-tests.ts
   create src/main/webapp/app/typings.d.ts
   create src/main/webapp/app/config/constants.ts
   create src/main/webapp/app/config/dayjs.ts
   create src/main/webapp/app/config/axios-interceptor.ts
   create src/main/webapp/app/config/devtools.tsx
   create src/main/webapp/app/config/error-middleware.ts
   create src/main/webapp/app/config/logger-middleware.ts
   create src/main/webapp/app/config/notification-middleware.ts
   create src/main/webapp/app/config/store.ts
   create src/main/webapp/app/config/icon-loader.ts
   create src/main/webapp/app/app.scss
   create src/main/webapp/app/_bootstrap-variables.scss
   create src/main/webapp/app/entities/index.tsx
   create src/main/webapp/app/modules/home/home.tsx
   create src/main/webapp/app/modules/login/logout.tsx
   create src/main/webapp/app/modules/login/login.tsx
   create src/main/webapp/app/modules/login/login-modal.tsx
   create src/main/webapp/app/modules/home/home.scss
   create src/main/webapp/app/shared/reducers/index.ts
   create src/main/webapp/app/shared/reducers/action-type.util.ts
   create src/main/webapp/app/shared/reducers/authentication.ts
   create src/main/webapp/app/shared/reducers/application-profile.ts
   create src/main/webapp/app/modules/account/index.tsx
   create src/main/webapp/app/modules/account/activate/activate.tsx
   create src/main/webapp/app/modules/account/password/password.tsx
   create src/main/webapp/app/modules/account/register/register.tsx
   create src/main/webapp/app/modules/account/password-reset/init/password-reset-init.tsx
   create src/main/webapp/app/modules/account/password-reset/finish/password-reset-finish.tsx
   create src/main/webapp/app/modules/account/settings/settings.tsx
   create src/main/webapp/app/modules/account/register/register.reducer.ts
   create src/main/webapp/app/modules/account/activate/activate.reducer.ts
   create src/main/webapp/app/modules/account/password-reset/password-reset.reducer.ts
   create src/main/webapp/app/modules/account/password/password.reducer.ts
   create src/main/webapp/app/modules/account/settings/settings.reducer.ts
   create src/main/webapp/app/modules/administration/index.tsx
   create src/main/webapp/app/modules/administration/administration.reducer.ts
   create src/main/webapp/app/modules/administration/docs/docs.tsx
   create src/main/webapp/app/modules/administration/docs/docs.scss
   create src/main/webapp/app/modules/administration/configuration/configuration.tsx
   create src/main/webapp/app/modules/administration/health/health.tsx
   create src/main/webapp/app/modules/administration/health/health-modal.tsx
   create src/main/webapp/app/modules/administration/logs/logs.tsx
   create src/main/webapp/app/modules/administration/metrics/metrics.tsx
   create src/main/webapp/app/modules/administration/user-management/index.tsx
   create src/main/webapp/app/modules/administration/user-management/user-management.tsx
   create src/main/webapp/app/modules/administration/user-management/user-management-update.tsx
   create src/main/webapp/app/modules/administration/user-management/user-management-detail.tsx
   create src/main/webapp/app/modules/administration/user-management/user-management-delete-dialog.tsx
   create src/main/webapp/app/modules/administration/user-management/user-management.reducer.ts
   create src/main/webapp/app/shared/layout/footer/footer.tsx
   create src/main/webapp/app/shared/layout/header/header.tsx
   create src/main/webapp/app/shared/layout/header/header-components.tsx
   create src/main/webapp/app/shared/layout/menus/index.ts
   create src/main/webapp/app/shared/layout/menus/admin.tsx
   create src/main/webapp/app/shared/layout/menus/account.tsx
   create src/main/webapp/app/shared/layout/menus/entities.tsx
   create src/main/webapp/app/shared/layout/menus/menu-components.tsx
   create src/main/webapp/app/shared/layout/menus/menu-item.tsx
   create src/main/webapp/app/shared/layout/password/password-strength-bar.tsx
   create src/main/webapp/app/shared/util/date-utils.ts
   create src/main/webapp/app/shared/util/pagination.constants.ts
   create src/main/webapp/app/shared/util/entity-utils.ts
   create src/main/webapp/app/shared/auth/private-route.tsx
   create src/main/webapp/app/shared/error/error-boundary.tsx
   create src/main/webapp/app/shared/error/error-boundary-route.tsx
   create src/main/webapp/app/shared/error/page-not-found.tsx
   create src/main/webapp/app/shared/DurationFormat.tsx
   create src/main/webapp/app/shared/model/user.model.ts
   create src/main/webapp/content/images/jhipster_family_member_0.svg
   create src/main/webapp/content/images/jhipster_family_member_0_head-192.png
   create src/main/webapp/app/shared/layout/header/header.scss
   create src/main/webapp/content/images/jhipster_family_member_0_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_0_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_0_head-512.png
   create src/main/webapp/app/shared/layout/footer/footer.scss
   create src/main/webapp/content/images/jhipster_family_member_1.svg
   create src/main/webapp/content/images/jhipster_family_member_1_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_1_head-512.png
   create src/main/webapp/content/images/jhipster_family_member_2.svg
   create src/main/webapp/content/images/jhipster_family_member_2_head-192.png
   create src/main/webapp/app/shared/layout/password/password-strength-bar.scss
   create src/main/webapp/content/images/jhipster_family_member_2_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_2_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_2_head-512.png
   create src/main/webapp/content/images/jhipster_family_member_3.svg
   create src/main/webapp/content/images/jhipster_family_member_3_head-192.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-256.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-384.png
   create src/main/webapp/content/images/jhipster_family_member_3_head-512.png
   create src/main/webapp/content/images/logo-jhipster.png
   create src/main/webapp/favicon.ico
   create src/main/webapp/swagger-ui/dist/images/throbber.gif
   create .eslintignore
   create src/main/webapp/manifest.webapp
   create src/main/webapp/WEB-INF/web.xml
   create src/main/webapp/robots.txt
   create src/main/webapp/app/config/axios-interceptor.spec.ts
   create src/main/webapp/app/config/notification-middleware.spec.ts
   create src/main/webapp/app/shared/reducers/application-profile.spec.ts
   create src/main/webapp/app/shared/reducers/authentication.spec.ts
   create src/main/webapp/app/shared/util/entity-utils.spec.ts
   create src/main/webapp/app/shared/auth/private-route.spec.tsx
   create src/main/webapp/app/shared/error/error-boundary.spec.tsx
   create src/main/webapp/app/shared/error/error-boundary-route.spec.tsx
   create src/main/webapp/app/shared/layout/header/header.spec.tsx
   create src/main/webapp/app/shared/layout/menus/account.spec.tsx
   create src/main/webapp/app/modules/administration/administration.reducer.spec.ts
   create src/main/webapp/app/modules/account/register/register.reducer.spec.ts
   create src/main/webapp/app/modules/account/activate/activate.reducer.spec.ts
   create src/main/webapp/app/modules/account/password/password.reducer.spec.ts
   create src/main/webapp/app/modules/account/settings/settings.reducer.spec.ts
   create src/main/webapp/app/modules/administration/user-management/user-management.reducer.spec.ts
   create src/test/javascript/e2e/modules/account/account.spec.ts
   create src/test/javascript/e2e/modules/administration/administration.spec.ts
   create src/test/javascript/e2e/util/utils.ts
   create src/test/javascript/e2e/page-objects/base-component.ts
   create src/test/javascript/e2e/page-objects/navbar-page.ts
   create src/test/javascript/e2e/page-objects/signin-page.ts
   create src/test/javascript/protractor.conf.js
   create src/test/javascript/e2e/page-objects/password-page.ts
   create src/test/javascript/e2e/page-objects/settings-page.ts
   create src/test/javascript/e2e/page-objects/register-page.ts
   create src/main/webapp/content/css/loading.css
   create src/main/webapp/404.html
   create src/main/webapp/index.html
   create src/main/webapp/swagger-ui/index.html
Git repository initialized.

Installing server dependencies using npm
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.1
npm ERR! Found: jest@25.2.3
npm ERR! node_modules/jest
npm ERR!   dev jest@"25.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jest@">=24 <25" from ts-jest@24.0.2
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"24.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/paul/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T13_43_11_664Z-debug.log
WARNING! Install of server dependencies failed!
To install your server dependencies manually, run: cd server && npm install

Changes to package.json were detected.

Running npm install for you to install the required dependencies.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'availity-reactstrap-validation@2.7.0',
npm WARN EBADENGINE   required: { node: '>= 5.0.0', npm: '^3.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
npm WARN EBADENGINE }
npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated redux-devtools-instrument@1.10.0: Package moved to @redux-devtools/instrument.
npm WARN deprecated redux-devtools@3.7.0: Package moved to @redux-devtools/core.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated redux-devtools-dock-monitor@1.2.0: Package moved to @redux-devtools/dock-monitor.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated redux-devtools-log-monitor@2.1.0: Package moved to @redux-devtools/log-monitor.
npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

> test@0.0.1-SNAPSHOT preinstall
> cd server && npm run lint:fix


> test@0.0.1 lint:fix
> npm run lint -- --fix


> test@0.0.1 lint
> eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts "--fix"


Oops! Something went wrong! :(

ESLint: 7.22.0

Error: Cannot read config file: /home/paul/Desktop/aaa/project/test/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /home/paul/Desktop/aaa/project/test/server/.server.eslintrc.json
    at Object.<anonymous> (/home/paul/Desktop/aaa/project/test/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/home/paul/Desktop/aaa/project/test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at module.exports (/home/paul/Desktop/aaa/project/test/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test/server
npm ERR! command failed
npm ERR! command sh -c eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts "--fix"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T13_44_22_568Z-debug.log
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test/server
npm ERR! command failed
npm ERR! command sh -c npm run lint -- --fix

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T13_44_22_596Z-debug.log
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test
npm ERR! command failed
npm ERR! command sh -c cd server && npm run lint:fix

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T13_44_22_655Z-debug.log
ERROR! Command failed with exit code 2: npm install
Error: Command failed with exit code 2: npm install
    at makeError (/home/paul/.nvm/versions/node/v14.16.0/lib/node_modules/yeoman-environment/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/paul/.nvm/versions/node/v14.16.0/lib/node_modules/yeoman-environment/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  shortMessage: 'Command failed with exit code 2: npm install',
  command: 'npm install',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Expected behavior**
It should generate an app without errors

**Desktop (please complete the following information):**
-   OS: Ubuntu 20.10

**NHipster configuration**
see output above

**Comment by amanganiello90** [comment]
HI @pwujek , thanks for the issue. It seems that you have problem with the npm install of the server folder, the generation is ok.

**Comment by pwujek** [comment]
`npm install` at root.

```bash
✘-1 ~/Desktop/aaa/project/test [master L|…26] 
10:11 $ npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'availity-reactstrap-validation@2.7.0',
npm WARN EBADENGINE   required: { node: '>= 5.0.0', npm: '^3.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '7.6.3' }
npm WARN EBADENGINE }

> test@0.0.1-SNAPSHOT preinstall
> cd server && npm run lint:fix


> test@0.0.1 lint:fix
> npm run lint -- --fix


> test@0.0.1 lint
> eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts "--fix"


Oops! Something went wrong! :(

ESLint: 7.22.0

Error: Cannot read config file: /home/paul/Desktop/aaa/project/test/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /home/paul/Desktop/aaa/project/test/server/.server.eslintrc.json
    at Object.<anonymous> (/home/paul/Desktop/aaa/project/test/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/home/paul/Desktop/aaa/project/test/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at module.exports (/home/paul/Desktop/aaa/project/test/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/home/paul/Desktop/aaa/project/test/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test/server
npm ERR! command failed
npm ERR! command sh -c eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts "--fix"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T14_12_00_505Z-debug.log
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test/server
npm ERR! command failed
npm ERR! command sh -c npm run lint -- --fix

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T14_12_00_535Z-debug.log
npm ERR! code 2
npm ERR! path /home/paul/Desktop/aaa/project/test
npm ERR! command failed
npm ERR! command sh -c cd server && npm run lint:fix

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T14_12_00_564Z-debug.log
```

`npm install` in server:

```bash
✔ ~/Desktop/aaa/project/test/server [master L|…26] 
10:14 $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test@0.0.1
npm ERR! Found: jest@25.2.3
npm ERR! node_modules/jest
npm ERR!   dev jest@"25.2.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer jest@">=24 <25" from ts-jest@24.0.2
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"24.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/paul/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2021-05-12T14_14_14_524Z-debug.log
```

**Comment by amanganiello90** [comment]
I think that your nodejs version is incompatible. Please install node 10 and check it.

**Comment by pwujek** [comment]
Can you please add this requirement to the README.md?

These are my currently installed versions.

```bash
✔ ~/Desktop/aaa/project/events [master|⚑ 1] 
09:41 $ npm --version
7.6.3
✔ ~/Desktop/aaa/project/events [master|⚑ 1] 
10:25 $ node --version
v14.16.0
```

**Comment by amanganiello90** [comment]
It is your dirty nodejs environment. It does not exist a version requirement. Besides in test integration pipeline is used your v14.16.0 version : https://github.com/jhipster/generator-jhipster-nodejs/blob/eb0e62b1d362bb3e98f307137bf9c6c31cdace25/.github/workflows/test-integration-angular.yml#L12

**Comment by pwujek** [comment]
I ran this test because I encountered problems trying to do a production build, can you please explain how a node environment gets 'dirty'?

**Comment by amanganiello90** [comment]
Sometimes npm caches packages causing errors for next npm command. Try to clean cache or reinstall nodejs:

- https://reactgo.com/npm-clear-cache/

**Comment by pwujek** [comment]
Thank-you.

Changing to the down-level version worked. I will now have to try re-building my main project again.

Installing node 12.18.2 wiped out previous npm caches and global node_modules, even requiring a reinstall of nHipster.

**Comment by amanganiello90** [comment]
Thank you for chat contribution! You are welcome! 

So I consider resolved this ticket and close it.
