### ISSUE TITLE
Impossible to upgrade JHipster, Impossible to run it

### ISSUE THREAD

**Issue by shai-almog** [jhipster/generator-jhipster-nodejs#257]
Running 
```
jhipster  --blueprints nodejs
```

I see 

```
  JHipster update available: 7.2.0 (current: 7.0.1)
```

So naturally I did:

```
npm --force install -g generator-jhipster
```

And it worked a lot on installing but jhipster remained the same (Using Mac OS Big Sur on Intel). Uninstalled it, reinstalled. Reinstalled via brew etc. It all results in the same odd old version.

Unfortunately this gets worse. After finishing the wizard no matter what I do I get the following exception (at the end of the full output below):

```
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at /usr/local/lib/node_modules/generator-jhipster-nodejs
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at /usr/local/lib/node_modules/generator-jhipster-nodejs
INFO! Error parsing options for generator jhipster-nodejs:app, error: Error: This is a JHipster blueprint and should be used only like jhipster --blueprints nodejs
     info Using blueprint generator-jhipster-nodejs for app subgenerator


 ███╗   ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗  ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔██╗ ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╗██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚████║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝  ╚═══╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to NHipster (Jhipster NodeJS Official Blueprint) v2.0.0
This blueprint generates your backend in NodeJS with NestJS framework
 _______________________________________________________________________________________________________________

  For any questions or improvements refer to the stream lead at https://github.com/amanganiello90
  If you find NHipster useful, support and star the project at https://github.com/jhipster/generator-jhipster-nodejs
 _______________________________________________________________________________________________________________

 This NodeJS blueprint use these following configurations:

 1. NestJS Framework with swagger doc

 2. JWT or OAuth2 Passport security authentication

 3. TypeORM usage with SQLite development database and versioning/migration

 4. Initial load data seed with users (using auth roles) integrated with the angular/react client

 5. Eureka JS client registry

WARNING! Your Node version is not LTS (Long Term Support), use it at your own risk! JHipster does not support non-LTS releases, so if you encounter a bug, please use a LTS version first.
 ______________________________________________________________________________

  JHipster update available: 7.2.0 (current: 7.0.1)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? What is the base name of your application? BlogFrontEnd
     info Using blueprint generator-jhipster-nodejs for common subgenerator
     info Using blueprint generator-jhipster-nodejs for server subgenerator
     info Using blueprint generator-jhipster-nodejs for client subgenerator
     info Using blueprint generator-jhipster-nodejs for languages subgenerator
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *production* database would you like to use? MySQL or MariaDB
? Which *Framework* would you like to use for the client? React
? Do you want to generate the admin UI? No
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
? Would you like to enable internationalization support? No
? Please choose the native language of the application English
? Would you like to install other generators from the JHipster Marketplace? No
ERROR! Template file .huskyrc was not found at /usr/local/lib/node_modules/generator-jhipster-nodejs/generators/common/templates,/usr/local/lib/node_modules/generator-jhipster/generators/common/templates
Error: Template file .huskyrc was not found at /usr/local/lib/node_modules/generator-jhipster-nodejs/generators/common/templates,/usr/local/lib/node_modules/generator-jhipster/generators/common/templates
    at /usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/generators/generator-base.js:2208:25
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/generators/generator-base.js:2138:42
    at Array.map (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/generators/generator-base.js:2135:29
    at Array.map (<anonymous>)
    at module.exports.writeFilesToDisk (/usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/generators/generator-base.js:2134:45)
    at module.exports.writeFiles (/usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/generators/common/files.js:69:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/yeoman-generator/lib/index.js:1009:25)
    at /usr/local/lib/node_modules/generator-jhipster-nodejs/node_modules/run-async/index.js:49:25
```

## jhipster info

```
INFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

/Users/shai/temp/jhipster2
└── (empty)

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Zulu 8.44.0.11-CA-macosx) (build 1.8.0_242-b20)
OpenJDK 64-Bit Server VM (Zulu 8.44.0.11-CA-macosx) (build 25.242-b20, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v16.10.0

npm: 7.24.0

Docker version 20.10.8, build 3967b7d

docker-compose version 1.29.2, build 5becea4c


No change to package.json was detected. No package manager install will be executed.
```

**Comment by shai-almog** [comment]
I assumed this was because of my Mac setup so I went through the whole process on a Linux machine only to run into the same issue... 

```
jhipster info
INFO! Using JHipster version installed globally
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**


/home/ubuntu/BlogFrontEnd
└── (empty)

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

git version 2.25.1

node: v16.10.0

npm: 7.24.0

Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2

docker-compose version 1.27.4, build 40524192


No change to package.json was detected. No package manager install will be executed.
```

**Comment by amanganiello90** [comment]
Thanks for the issue, but the upgrade of hipster is not related to this node's blueprint.
