### ISSUE TITLE
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0

### ISSUE THREAD

**Issue by ranraj** [jhipster/generator-jhipster-nodejs#266]
**Describe the bug**
npm install failed with the following error in nhipster generated code.

```
> eslint . --ignore-path .server.eslintignore --no-eslintrc --config .server.eslintrc.json --ext .js,.ts "--fix"


Oops! Something went wrong! :(

ESLint: 7.23.0

Error: Cannot read config file: /Users/******/Documents/rspace/learn/nodejhipster/node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
Referenced from: /Users/******/Documents/rspace/learn/nodejhipster/server/.server.eslintrc.json
    at Object.<anonymous> (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/eslint-config-prettier/@typescript-eslint.js:1:69)
    at Module._compile (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at module.exports (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/@eslint/eslintrc/node_modules/import-fresh/index.js:32:59)
    at loadJSConfigFile (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/@eslint/eslintrc/lib/config-array-factory.js:225:16)
    at loadConfigFile (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/@eslint/eslintrc/lib/config-array-factory.js:309:20)
    at ConfigArrayFactory._loadConfigData (/Users/******/Documents/rspace/learn/nodejhipster/node_modules/@eslint/eslintrc/lib/config-array-factory.js:609:42)
npm ERR! code 2
npm ERR! path /Users/******/Documents/rspace/learn/nodejhipster
npm ERR! command failed
npm ERR! command sh -c cd server && npm run lint:fix

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/******/.npm/_logs/2022-03-24T03_45_35_629Z-debug-0.log
```

**To Reproduce**
```
mkdir appname
cd appname
wget https://github.com/jhipster/generator-jhipster-nodejs/raw/master/docker/Dockerfile
docker build -t jhipster-generator-nodejs:latest .
docker run -it --rm -v $PWD:/home/jhipster/app jhipster-generator-nodejs jhipster --blueprints nodejs
npm install
```

**Expected behavior**
Expected basic nodejs application up and running from the docker container.

**Screenshots**
<img width="733" alt="Screenshot 2022-03-24 at 9 18 37 AM" src="https://user-images.githubusercontent.com/3829611/159838351-3a1a8969-101d-469a-933b-94778c3b0733.png">

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser : Chrome
-   Version : Mac 10.15.7

**NHipster configuration**
jhipster info
```
 docker run -it --rm -v $PWD:/home/jhipster/app jhipster-generator-nodejs jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
INFO! No custom sharedOptions found within blueprint: generator-jhipster-nodejs at /home/jhipster/app/node_modules/generator-jhipster-nodejs
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at /home/jhipster/app/node_modules/generator-jhipster-nodejs
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**
```
```
app@0.0.1-SNAPSHOT /home/jhipster/app
+-- generator-jhipster-nodejs@2.0.0
| `-- generator-jhipster@7.0.1 deduped
`-- generator-jhipster@7.0.1

```

```
##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "applicationType": "monolith",
    "baseName": "app",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1648091633565,
    "serverPort": "8081",
    "packageName": "com.jhipster.node",
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/jhipster/node",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "serviceDiscoveryType": false,
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "enableHibernateCache": true,
    "reactive": false
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

node: v14.16.0

npm: 8.5.5


No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.
```

.yo-rc.json
````
{
  "generator-jhipster": {
    "blueprints": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "otherModules": [
      {
        "name": "generator-jhipster-nodejs",
        "version": "2.0.0"
      }
    ],
    "applicationType": "monolith",
    "baseName": "app",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1648091633565,
    "serverPort": "8081",
    "packageName": "com.jhipster.node",
    "databaseType": "sql",
    "devDatabaseType": "sqlite",
    "prodDatabaseType": "mysql",
    "authenticationType": "jwt",
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/jhipster/node",
    "jwtSecretKey": "YzAwYjYxN2M1MjM2YWI3MDA0YTJiMDVjZmE4Y2NkNTkyOGZiODRlMzRmZThhZmMyMzhmOWU3NTg1NGZlNjA5NjRkYjNkZWFiOGJiZTNhOGI3ODcyYWMzNWQ4ZWEzNmNhYzMxMmE3MGIyNTNkYzdmZjNhZGIyODY2YzNhOTVjZjc=",
    "serviceDiscoveryType": false,
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en"],
    "cacheProvider": "ehcache",
    "buildTool": "maven",
    "enableHibernateCache": true,
    "reactive": false
  }
}

```
 

**Additional context**
Add any other context about the problem here.

**Comment by vanpipy** [comment]
Any response?  the same error was caugth with nhipster@7.0.1

**Comment by vanpipy** [comment]
Any response or waiting the upgrade of the nhipster?

**Comment by amanganiello90** [comment]
Hi @ranraj,
There are some issue I resolving in order to upgrade nhipster.
Now we have to fix github actions plans

**Comment by vanpipy** [comment]
> Hi @ranraj, There are some issue I resolving in order to upgrade nhipster. Now we have to fix github actions plans

Is there a fixing roadmap? Maybe give a hand for the simple part.

**Comment by vanpipy** [comment]
> There is not a roadmap. If you want, you could create a feature branch and resolve in order:
> 
> * github actions plan
> * nhipster upgrade

What is the content of `nhipster upgrade`? Did it mean to running the application created by `nhipster`?

**Comment by amanganiello90** [comment]
The nhipster upgrating means two things:
- Upgrade jhipster platform to the last version (from 7.0.1 to 7.9.3) --> https://github.com/jhipster/generator-jhipster-nodejs/blob/6ac167584ac4c7a73e13abb72d95cd9d0bba6830/package.json#L59
- Upgrade nestjs and other library versions --> https://github.com/jhipster/generator-jhipster-nodejs/blob/v2.0.0/generators/server/templates/server/package.json.ejs
