### ISSUE TITLE
Error while creating nodejs microservice app

### ISSUE THREAD

**Issue by srinivasansuit** [jhipster/generator-jhipster-nodejs#535]
**Describe the bug**
user is not defined
ReferenceError: C:\Users\name\AppData\Roaming\npm\node_modules\generator-jhipster-nodejs\generators\node-server\templates\server\src\web\rest\user.controller.ts.ejs:4
    2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
    3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
 >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
    5| import { HeaderUtil } from '../../client/header-util';
    6| import { Request } from '../../client/request';
    7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';

**To Reproduce**

1. Run the jhipster --blueprints nodejs
Welcome to JHipster v8.5.0

? What is the base name of your application? codecompiler
? Which *type* of application would you like to create? Microservice application
? As you are running in a microservice architecture, on which port would like your server to run? It should be unique to
 avoid port conflicts. 8081
? Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
? Which *production* database would you like to use? PostgreSQL
? Which *framework* would you like to use as microfrontend? No client
ERROR! An error occured while running jhipster-nodejs:node-server#writingTemplateTask
ERROR! ERROR! C:\Users\Srinivasan\AppData\Roaming\npm\node_modules\generator-jhipster-nodejs\generators\node-server\templates\server\src\web\rest\user.controller.ts.ejs:4
    2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
    3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
 >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
    5| import { HeaderUtil } from '../../client/header-util';
    6| import { Request } from '../../client/request';
    7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';
user is not defined
ReferenceError: C:\Users\Srinivasan\AppData\Roaming\npm\node_modules\generator-jhipster-nodejs\generators\node-server\templates\server\src\web\rest\user.controller.ts.ejs:4
    2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
    3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
 >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
    5| import { HeaderUtil } from '../../client/header-util';
    6| import { Request } from '../../client/request';
    7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';

**Expected behavior**
It should generate microservice application without front end to use it

**Screenshots**

**Desktop (please complete the following information):**

- OS: windowns 11 home

**NHipster configuration**

**Additional context**

**Comment by awssa1412** [comment]
Hi team,

Any update for this issue? We're facing the same error when generate a new microservices project.

Thanks,

**Comment by DanielFran** [comment]
@awssa1412 we will release a new version 8.8.0.
Please confirm issue is fixed
Thanks

**Comment by srinivasansuit** [comment]
No,  it didn't. I manually edited the file referenced in the error(C:\Users\name\AppData\Roaming\npm\node_modules\generator-jhipster-nodejs\generators\node-server\templates\server\src\web\rest\user.controller.ts.ejs:4) and updated it to fix the issue. 
Similar issues in multiple files, fixed all of them manually editing it. 
It's a temporary fix, but not an permanent resolution.

**Comment by jlopezjuy** [comment]
i have same error
```
 2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
      3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
   >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
      5| import { HeaderUtil } from '../../client/header-util';
      6| import { Request } from '../../client/request';

```

**Comment by mshima** [comment]
I confirm, microservices should not generate code related to user.

**Comment by jlopezjuy** [comment]
hi, im trying to create a new microservice on a empoty folder, and i have this error:

```

jhipster --version
9.3.0

nhipster --version
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs
4.0.0 (generator-jhipster 9.2.0)


nhipster                         
INFO! No custom commands found within blueprint: generator-jhipster-nodejs at /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs

 ███╗   ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
 ████╗  ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
 ██╔██╗ ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
 ██║╚██╗██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
 ██║ ╚████║ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
 ╚═╝  ╚═══╝ ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝

                            https://www.jhipster.tech

Welcome to NHipster (Jhipster NodeJS Official Blueprint) v4.0.0
This blueprint generates your backend in NodeJS with NestJS framework
 _______________________________________________________________________________________________________________

  For any questions or improvements refer to the stream lead at https://github.com/amanganiello90
  If you find NHipster useful, support and star the project at https://github.com/jhipster/generator-jhipster-nodejs
 This NodeJS blueprint use these following configurations:

 1. NestJS Framework with swagger doc

 2. JWT or OAuth2 Passport security authentication

 3. TypeORM usage with SQLite development database and versioning/migration

 4. Initial load data seed with users (using auth roles) integrated with the angular/react client

 5. Eureka JS client registry

Could not retrieve version of blueprint 'jhipster-nodejs:server:bootstrap'
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: /Users/juanlopez/Proyectos/Propios/StockMulti/vendora-custom-work
 _______________________________________________________________________________________________________________

WARNING!  ______________________________________________________________________________

  JHipster update available: 9.3.0 (current: 9.2.0)

  Run npm install -g generator-jhipster to update.

 ______________________________________________________________________________

✔ What is the base name of your application? vendoraCustomWork
Could not retrieve version of blueprint 'jhipster-nodejs:node-server:bootstrap'
✔ Which *type* of application would you like to create? Microservice application
Could not retrieve version of blueprint 'jhipster-nodejs:server'
Could not retrieve version of blueprint 'jhipster-nodejs:node-server'
✔ As you are running in a microservice architecture, on which port would like your server to run? It should be unique to avoid port conflicts. 8089
`list` prompt is deprecated. Use `select` prompt instead.
✔ Which *type* of authentication would you like to use? JWT authentication (stateless, with a token)
`list` prompt is deprecated. Use `select` prompt instead.
✔ Which *production* database would you like to use? PostgreSQL
Could not retrieve version of blueprint 'jhipster-nodejs:docker'
Could not retrieve version of blueprint 'jhipster-nodejs:client'
✔ Which *framework* would you like to use as microfrontend? No client
ERROR! An error occured while running jhipster-nodejs:node-server#writingTemplateTask
ERROR! ERROR! Error rendering template /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs to /Users/juanlopez/Proyectos/Propios/StockMulti/vendora-custom-work/server/src/web/rest/user.controller.ts: TypeError: /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs:4
    2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
    3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
 >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
    5| import { HeaderUtil } from '../../client/header-util';
    6| import { Request } from '../../client/request';
    7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';

Cannot read properties of undefined (reading 'dtoClass')
Error: Error rendering template /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs to /Users/juanlopez/Proyectos/Propios/StockMulti/vendora-custom-work/server/src/web/rest/user.controller.ts: TypeError: /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs:4
    2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
    3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
 >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
    5| import { HeaderUtil } from '../../client/header-util';
    6| import { Request } from '../../client/request';
    7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';

Cannot read properties of undefined (reading 'dtoClass')
    at renderTemplate (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/dist/generators/base-core/generator.js:902:23)
    at async Promise.all (index 4)
    at async default.writeFiles (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/generator-jhipster/dist/generators/base-core/generator.js:1003:24)
    at async default.writingTemplateTask (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/generator.js:211:9)
    at async default.executeTask (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/yeoman-generator/dist/actions/lifecycle.js:265:13)
    at async runLoop.add.once (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/yeoman-environment/dist/environment-base.js:383:17) {
  [cause]: TypeError: /Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs:4
      2| import { AuthGuard,  Roles, RolesGuard, RoleType } from '../../security';
      3| import { PageRequest, Page } from '../../domain/base/pagination.entity';
   >> 4| import { <%= user.dtoClass%> } from '../../service/dto/user.dto';
      5| import { HeaderUtil } from '../../client/header-util';
      6| import { Request } from '../../client/request';
      7| import { LoggingInterceptor } from '../../client/interceptors/logging.interceptor';
  
  Cannot read properties of undefined (reading 'dtoClass')
      at default.eval ("/Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs":12:31)
      at user.controller.ts (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/mem-fs-editor/node_modules/ejs/lib/esm/ejs.js:688:17)
      at ejs.render (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/mem-fs-editor/node_modules/ejs/lib/esm/ejs.js:419:37)
      at fileTransform (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/mem-fs-editor/dist/actions/copy-tpl-async.js:22:29)
      at async copySingleAsync (file:///Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/node_modules/mem-fs-editor/dist/actions/copy-async.js:103:31) {
    path: '/Users/juanlopez/.nvm/versions/node/v24.18.0/lib/node_modules/generator-jhipster-nodejs/generators/node-server/templates/server/src/web/rest/user.controller.ts.ejs'
  }
}
```
